### ISSUE TITLE
Hashed Time-Locked Contracts Discussion

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/AIPs#102]
Discussion related to HTLC AIP: https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-102.md

**Comment by Moustikitos** [comment]
Nice work !

- Why the HTLC_Refund transaction type ? (Is HTLC_Lock timelock parameter not enough ?)

**Comment by kristjank** [comment]
You mean auto refund? when expired?

**Comment by Moustikitos** [comment]
Yes, actually there is no "real" token transfer during timelock if no HTLC_Claim tx is sent.

**Comment by Moustikitos** [comment]
Okay, explanation of HTLC_refund tx [here](https://youtu.be/ueCi6I4uPHw) is crystal clear.
Nice work !
