### ISSUE TITLE
BridgeChain Transaction Type Discussion

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/AIPs#103]
BridgeChain Transaction Types Open Discussion https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-103.md

**Comment by roks0n** [comment]
I can see that these transaction types will likely be used for name squatting. For example people registering Google, Facebook, Libra, Microsoft for businesses and bridge chain names as well as using fake or similar names for scamming purposes.

Are there any ideas on how to prevent this from happening? I'm w/o any, hence the question. :)

**Comment by MatthewDC** [comment]
Yes, details on how we intend to provide for added verification will be discussed more in depth as we release more details of the marketplace.
