### ISSUE TITLE
AIP 126: Safer cold storage using Ark covenants

### ISSUE THREAD

**Issue by moazzamak** [ArkEcosystem/AIPs#126]
Discussion thread about [`AIP 126: Safer cold storage using Ark covenants`](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-126.md)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please review and correct it.

**Comment by moazzamak** [comment]
Discussion on slack 


cam (cams_yellow_jacket):boogieark3: 12:41 AM
I like it mak 
But if unless a hacker is specifically targeting someone, they'd have to know that persons address is a covenant address ahead of time to deter them.
Is it typical that hackers specifically target certain people for their keys or are they more often casting a wide net trying to get anyone's keys?
Also, I think in addition to the poison address, there could be a diversion address? Ie if a tx is sent from a diversion address then the tokens aren't burned but are instead sent to another address. Like a friend or someone your trust. Idk how doable that'd be though. :sweat_smile:
Vakindu 2:07 AM
joined #delegate.
mak 6:02 AM
High net worth individuals are targeted with all kinds of social engineering and other hacking methods.
Problem with "rescuing" the money is that it creates incentive for fraud. It would become a tool used to basically double spend others so that option is not allowed.
Also the attacker would know about the rescue key/address and the game theoretic solution we have now would be broken again since they can just target for that instead of the normal keys.
cam (cams_yellow_jacket):boogieark3: 6:34 AM
:thinking_face:
Tin [Echo] [arktoshi.com] [arkapps.io] 6:40 AM
:thinking_face:
Tarek // Ki Foundation 7:47 AM
mak  I just read the AIP quickly. Great job! Just wondering, is the "3 days" recommended config a guess or do you have any specific rational for this? And how do you think this confirmation delay would impact the use of a cold wallet as no token is really usable before a "3 days" delay. In other words, would the set delay depend on the intended usage of the cold storage?
mak 7:50 AM
It's a parameter configurable by the user but I recommend using at least 3 days. Because once this time is over there is no way to burn the amount so if the time is too short then the deterrence factor becomes negligible.
By definition cold storage wallets shouldn't be used too often so I imagine no one will have issues with the 3 day time
Tarek // Ki Foundation 7:58 AM
I agree that if the time is too short the deterrence factor is negligible. But I think a short time is more like a couple of hours and a long enough is more like 1 day max. It is true that cold storage are not used often but this doesn't mean they should not be used in a relatively quick manner when needed.
mak 8:00 AM
I would say that should be up to the user
I know I don't check my addresses too often and I'm still one of the active ones
cam (cams_yellow_jacket):boogieark3: 8:25 AM
Same.
Could always implement a service that sends an alert to the user too when a send is being attempted.
