### ISSUE TITLE
API 13: Support signing transactions

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/AIPs#19]
There should be more functionality to the `ark:` schema besides just sending transactions. A few things I'd like to see it supporting:

- Sign and verify messages
- Vote for a delegate
- Add a new network
- Add a new contact
- Switch to a specific peer
- Send a transaction using a specific peer

**Comment by fix** [comment]
yes, together with that, put AIP11 serialisation so the length of the data is a lot shorter
