### ISSUE TITLE
AIP 7: Proxy Voting

### ISSUE THREAD

**Issue by Doweig** [ArkEcosystem/AIPs#2]
https://github.com/cosmos/cosmos/issues/43#issuecomment-264106839

> back in 2014, we were running BitShares in version 1.0 which had exactly the problems you described. Today, with Bitshares 2.0, we have proxy voting. It allows shareholders to direct their voting power to another account which then has more total voting power. This allows to establish a group of arbitrary size to be able to react quickly shall it be necessary (e.g. fire a witness)

Witness aka Forging delegates. That is a good idea to make the network more responsive.

**Comment by 2mdoty** [comment]
Would very much like to see proxy voting. This will help encourage voter participation, and lays the foundation to use Ark code for liquid democracy, https://en.wikipedia.org/wiki/Delegative_democracy , article by Dominik Schiener, https://medium.com/organizer-sandbox/liquid-democracy-true-democracy-for-the-21st-century-7c66f5e53b6f#.9uw31kqq1

**Comment by Doweig** [comment]
Nice! Pasting here the pictures from 2mdoty's links:

| Wikipedia | Dominik Schiener |
|:----------:|:-----------------:|
| <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Democracy.svg/340px-Democracy.svg.png" height="400px"/> | <img src="https://cdn-images-1.medium.com/max/1200/0*Qev_LxQYu9KsNAQt." height="400px"/> |

**Comment by fix** [comment]
proxy voting has the advantage to tweak dpos consensus so stakeholders AND good reputation can weight in the process of choosing active delegates.
