### ISSUE TITLE
AIP draft Pluggable Smart Contract Engine

### ISSUE THREAD

**Issue by RockHoward** [ArkEcosystem/AIPs#23]
Rather than tightly integrate the EVM smart contract engine with the Ark VM, it would be smarter to make this another pluggable subsystem. The upside for this is that the blockchain developer using Ark can choose which smart contract engine makes sense (and there are alternatives to EVM that have a lot of merit), but also, even if they use EVM, they can specify and lockdown exactly which version of EVM they will deploy.

If you don't do something like this then updating the EVM within the ArkVM periodically as the EVM itself evolves will turn into an ongoing problem. On the one hand ArkVM will typically support an out-of-date version of EVM but the pressure to update the EVM within the ArkVM will be countered by the demands of existing projects who will want the Ark team to continue to support their deployments. 

With a pluggable interface for smart contract engines third parties can step in and provide and support alternative smart contract engine solutions (and versions thereof) thus freeing the Ark team from that headache while also providing the opportunity to leapfrog the EVM in terms of capability as new smart contract engines emerge in the marketplace.

**Comment by kristjank** [comment]
Something we are thinking about for a while now. Would be good if you provided more details on how and where do you see this, but this is the correct patch to provide pluggable smart contracts or dapps via plugin system.

**Comment by doubled1c3** [comment]
Intriguing!
