### ISSUE TITLE
Discussion: AIP-16

### ISSUE THREAD

**Issue by arkmoon** [ArkEcosystem/AIPs#28]
We had an extensive discussion on Slack, and was told I should document some of our concerns here. So I will try to do so in order to continue discussion regarding dynamic fees.

My worry is specifically the new **feeMultiplier** constant that was introduced in this AIP. Everything else in this AIP makes sense, for example it makes sense that a transaction with a full 255 character vendorField be more expensive than a transaction with a blank vendorField.

I have three concerns or arguments against this feeMultiplier, and the concept transactions being dropped due to not having a sufficient fee attached to it:

1. Most delegates are not going to be motivated to have high fees at all. There will be a race to the bottom as delegates compete against each other and lower their feeMultilpliers to entice voters. So at that point any delegate stupid enough to maintain high fees will simply stop forging transactions and eventually be voted out. So we're already starting at the bottom.

2. For the end user creating a transaction, there is absolutely no benefit to adding a higher fee than the absolute bare minimum. A user who sets a maximum fee will not have their transaction processed any faster than someone with the minimum fee. So, again, we're at the bottom.

3. Finally, with the ability for delegates to reject a transaction based on too-small fees, now a user may have to **wait up to 6 hours** before they find out that their transaction was discarded by the network because their fee was too low. It would be physically impossible to use Ark in an commerce setting because a user wouldn't be able to leave the store with their goods until they found out their transaction was accepted or failed for some reason.

I'm open to any discussion or clarification on any of the points above. I only want the best for the Ark network and its end users, and we want it to be as intuitive as possible.

What we have right now is brilliant. A user sees how much a transaction is going to cost based on the type of transaction, and they don't have to do anything else. Their transaction is accepted within 8 seconds. Bitcoin and Ethereum can't beat that on their best days.

**Comment by arkmoon** [comment]
To sum up our latest discussion on Slack. If we implement a slider on the Desktop wallet that displays the absolute upper delegate fee and the lowest delegate fee, and tell them based on that their transaction takes between 8 seconds minimum and 6-8 minutes maximum, then the user can pick their fee and is guaranteed to get it forged and shouldn't get dropped because they don't meet any delegate minimums.

**Comment by fix** [comment]
@arkmoon can we close this now?
