### ISSUE TITLE
AIP - Sybil Attack / Exclude Relays from Consensus

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/AIPs#34]
I think we should discuss about:

- Calculating Quorum only be delegate nodes and exclude relays from the calculation
- Changing Delegate count to a prime number like 53 to avoid network splits
- Invent an economic model to give back influence on consensus to relays later (if needed)

What do you think?

**Comment by geopsllc** [comment]
Fully agree with points 1 and 2. Not sure 3 is needed at all.

**Comment by doubled1c3** [comment]
Fully agree with points 1 and 2, not sure 3 is necessary. I'm glad this is getting brought up and hope discussions continue. I'm assuming jarunik is saying "Calculating quorum only be *forging* delegate nodes and exclude relays

Edit: Seems like a full AIP should be created for this at some point...

**Comment by fix** [comment]
Just to clarify here. This issue is actually one solution to prevent sybil attack. I have renamed the title to reflect this

**Comment by fix** [comment]
to answer points:
- making relay nodes less useful to run. but that could be a possibility
- i still don't understand why we need a prime number. With 53 you can have a split like (3 ; 25 ; 25) or [2k+1 ; (N-1)/2 - k ; (N-1)/2 - k] whatever 0 < k < N/4
- needs creativity ;)

**Comment by Jarunik** [comment]
I suggest that we focus on point one and address the sybil attack as it has highest priority. You are right with prime numbers. Does not help much if it is a multiple split. And relay node rewards can be addressed later.

**Comment by zillionn** [comment]
1. Let's say, theoretically, we can distinguish the peers by forgers and relays.
2. How about the relays to have a lower weight in the quorum decision than the forgers? For instance, now we use `1` for every peer, how about if it's a relay to use `0.2` or something?

**Comment by Jarunik** [comment]
To just give them lower weight does not help much... then you just launch 5 times more relays in an attack.
