### ISSUE TITLE
AIP-26: URI Scheme Improvements - Discussion

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/AIPs#42]
Discussion thread for AIP 26: [URI Scheme Improvements](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-26.md)

**Comment by fix** [comment]
There is one thing that needs to be addressed: `protocol://` is a well known way to perform phishing attacks. This needs to be clarified in each call.

**Comment by vmunich** [comment]
If I understood correctly, that's also present in the currently implemented [AIP-13](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-13.md). If an URI is malformed, clients will just reject it. 

Once a client processes an URI, it should display a confirmation page before executing the call. All Ark clients that support AIP-13 at the moment display a confirmation page before executing the call.

**Comment by fix** [comment]
that is a bit more tricky. Let's give an example
let say we have defined a protocol `ark://pay/amount/currency/address` to pay `amount`  `currency` to `address` for instance `ark://pay/10/eur/AXC8TZvrzXEzkVDsmbEg1QbnnHCA6b5eAm` 

The system will pass over this to wallet, and the wallet will perform the following procedure:
- check wallet `address` balance
- check price ark/eur to calculate ratio
- check user wallet for available balance
- more interaction with network/internet
- etc...
- user send signed transaction

Now an attacker is able to TRIGGER a reaction from a wallet. He will spawn a few normal nodes.
He will create a special 'pay with ark' website, where he will linked IP to the `address` he will propose to pay.

By listening what happens to network he can start matching IP with user wallet, try to identified the wallet version the user is using, even if the user does not pay anything in the end. If the site is starting to be used, the attacker can map quite largely the users of ark and their locations, even track them, matching different IPs/wallets with one user.

Now imagine that you add possibilities in the URI scheme to add phone numbers or emails for confirmations, or a return server to post whatever data...

point is TRIGGER

**Comment by zillionn** [comment]
@fix Phishing attacks are possible with every link on every site/email.

What's your proposal?

**Comment by roks0n** [comment]
@fix you can already pinpoint wallets to certain IP even without a website by listening to what IPs are transactions originating from. If people care deeply about their privacy they should run their own relays.

How would phone numbers, emails be added to the URI? Via vendor field? If that happens I hope them to be encrypted. In case the website offering Ark Pay needs them, that should be explained in their Privacy policy and TOS. If it's some dodgy website, user should do their due diligence.
