### ISSUE TITLE
AIP - Add Nonces to prevent replay attacks

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/AIPs#46]
Add nonces to transactions in order to prevent replay attacks.

As soon as there is a transaction with a bigger nonce then the previous transaction in the pool becomes invalid.

That prevents attacks where you can store the transaction and later replay it even if the sender issued a replacement transaction.

With nonces you can replace unforged transactions while being sure that the old unforged yet signed transactions are invalidated.

**Comment by kristjank** [comment]
The aip for this is in progress for a while now.
