### ISSUE TITLE
AIP 3: Anonymous Vote

### ISSUE THREAD

**Issue by Doweig** [ArkEcosystem/AIPs#5]
Anonymous vote, you can’t see who voted for you. Would avoid people begging for votes and only making promises. If you can’t know who voted for you, vote swap is dead, you can only focus on actually making contributions, and ask community feedback

**Comment by 2mdoty** [comment]
Knowing source of votes enables profit sharing in the form of direct payments to voters from earnings and in the form of equity in funded projects. Also, it encourages community interaction between stakeholders and delegates. I would like to see an option for anonymizing proxies in voting, so voters can assign their votes to other accounts to vote for them.

**Comment by ghost** [comment]
I don't agree with this.  It affects the transparency of votes in the Ark.  Voting should stay public.  When votes are private, that is when you begin to question the source or if anything is going on behind the scenes.
