### ISSUE TITLE
AIP 5: Forging Secret

### ISSUE THREAD

**Issue by Doweig** [ArkEcosystem/AIPs#6]
Forging Secret, you would need both passphrases to generate a secret, that secret would be stored in the config.json and is what enables you to forge. That secret would prove your identity and includes a nounce (number). So if your server gets hacked you can generate a new secret with nounce + 1 so the previous secret (the one that was hacked) is not usable anymore. That way no more passphrase on servers, would also solve the forging/voting account separation. Since no key on server anymore, there’s no need to separate those accounts

**Comment by 2mdoty** [comment]
This would be a big improvement, so you don't lose your delegate name and brand if hacked.

**Comment by SpaceGuildIntern** [comment]
@fix Would something like this be possible with the new AIP11?

**Comment by reConNico** [comment]
@fix : Someone has this on his mind? Maybe in another way but this would be awesome to get more security for delegates.

**Comment by doubled1c3** [comment]
Seems beneficial

**Comment by zillionn** [comment]
https://blog.ark.io/new-ark-core-commander-eb704b7e75fd#31d4
