### ISSUE TITLE
Give powers to ARK Github Bot to post new AIP issue links to the Reddit

### ISSUE THREAD

**Issue by doubled1c3** [ArkEcosystem/AIPs#69]
Just so people can be informed that a new discussion has started so people can be informed, as AIPs are important :)

**Comment by ghost** [comment]
@doubled1c3 Thanks for opening this issue, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._
