### ISSUE TITLE
AIP 10: Automatic Profit Sharing

### ISSUE THREAD

**Issue by rrbest** [ArkEcosystem/AIPs#9]
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-10.md

TLDR: Allow delegates to use a specific transaction to set their profit sharing percentage. Then, pay this out automatically to voters at each of the delegate's forged block.

**Comment by fix** [comment]
There is one big drawback in this solution: it is extremely difficult to keep track of the distributed reward, since there is no tx.

one alternative is to add an extra list in the block header, that will track the distribution of shares:
{"address1":reward1,"address2":reward2}

The node should:
- check that all voters get their rewards proportionally to their vote weight
- not extra address get reward
- rewards are summing to ratio*2arks

That is time consuming. On the other hand doing manual txs are power consuming UNLESS they are done aggregating few blocks reward.

Also there might be an attack where a voter might try to vote/unvote after to grab as many rewards as he can....

**Comment by rrbest** [comment]
I think the vote/unvote attack is completely eliminated when voters are determined by round rather than by block. If you voted for a delegate and that vote determined their inclusion in the round, you would be entitled to their profit share as long as they successfully forged a block. Switching after this point would not entitle you to anything until the next round.

**Comment by doubled1c3** [comment]
Hmm. I have thoughts on this concept, a few actually.

I'm assuming that this system automatically and continuously "injects" rewards into wallets without creating transactions.

So first of all, there's a psychological value that is lost by removing a visible and real reward transaction.  You see, people love seeing a transaction appear in their wallet. There is an adrenaline rush there that spurs adoption.  In the early days of AOL, as a kid who logged on to hear "You've Got Mail!" it was a huge rush.  Email was so new and amazing.  "Someone has sent me a message! Awesome!!" Adults feel the same when they receive free magic Internet money as well.

Secondly, this system removes the delayed gratification felt after a day, week, or month of voting.  You hodled, you waited, you saved, and finally you earned.  There is a sense of accomplishment there.  You can also look back to see all of these "accomplishments" (transactions) and feel the feeling as well.  To have continuous returns gained in real-time, you just get less of that feeling, and get desensitized to it.

Ark magically appears in the wallet, so now the activity of the transactions don't add up to give you the correct final balance.  This seems like an accounting nightmare?

As there are no transactions, the amount and timestamp are not known, and income tax can't be assessed without weird and complex algorithms.  Seems like a huge ease of use problem?

Also, I think there is a legal merit to the delegates pushing a button and doing a voluntary payout, as opposed to the system autonomously distributing returns (without delegates executing a "Go" order).  I do support integrated tools that assist delegates in making easy payouts, but it should still be a manual action that they perform on a voluntary basis even if it's just pushing 1 button to pay all.  Offering a platform with guaranteed system payouts in exchange for investment seems legally awkward.  Perhaps I am missing something there, though.

If a response is made here, let me know on Slack as well, many thanks!

**Comment by MatthewDC** [comment]
We have discussed this in the past but there is a legal precedent that says that if the network itself is pushing a dividend to voters, for holding tokens and voting, that is essentially classified as a shareholder dividend. 

In our current model, the network itself is rewarding delegates for services rendered as network service providers and treats them as contractors providing a service and being compensated for said service. If that service provider decides to profit share with voters, that is their responsibility to determine any liability in regards to that practice, but the network itself isn't issuing a dividend which would classify it as an unregistered security. 

This is a sticking point for exchanges, especially major players like Binance and Bittrex. As soon as you have an ingrained network generated dividend they will de-list, as evidenced by the previous de-listing of Bitshares.
