### ISSUE TITLE
Atomic Swap between ark, ark-forks and lightning network

### ISSUE THREAD

**Issue by Moustikitos** [ArkEcosystem/AIPs#95]
Because it allows peer to peer exchanges (or decentralized exchanges), atomic swap is one of the biggest feature every blockchain try to reach. For now, [HTLC](https://en.bitcoin.it/wiki/Hashed_Timelock_Contracts) achievement on Bitcoin Network is the most promising procedure in that way.

[See on mermaidjs.github.io](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cbnBhcnRpY2lwYW50IEJBTFQgYXMgQm9iPGJyLz5BbHQgV2FsbGV0XG5wYXJ0aWNpcGFudCBCQVJLIGFzIEJvYjxici8-QXJrIFdhbGxldFxucGFydGljaXBhbnQgX0FSSyBhcyBBcmsgYmxvY2tjaGFpblxucGFydGljaXBhbnQgX0FMVCBhcyBBbHQgYmxvY2tjaGFpbjxici8-KEFyayBmb3JrKVxucGFydGljaXBhbnQgQUFSSyBhcyBBbGljZTxici8-QXJrIFdhbGxldFxucGFydGljaXBhbnQgQUFMVCBhcyBBbGljZTxici8-QWx0IFdhbGxldFxuXG5Ob3RlIG92ZXIgQkFMVCxCQVJLIDogQm9iIHdhbnRzIHRvIGJ1eSBBbHQgY29pbiB1c2luZzxici8-aGlzIEFyayBhbmQgZmluZHMgQWxpY2Ugd2hvbSBpczxici8-cmVhZHkgdG8gbWFrZSB0aGUgZGVhbC5cblxuQkFSSyAtPj4gX0FSSyA6IDQ4aC1mcm96ZW4gdHggd2l0aCBpbmNvbXBsZXRlIGFzc2V0XG5fQVJLIC0tPj4gX0FSSzogRmVlcyBhcmUgZ2l2ZW4gdG8gYSBibG9ja1xuX0FSSyAtPj4gK0FBUks6IEFsaWNlIGNhbiBjaGVjayB0aGUgQXJrIGFtb3VudCBvbiBoZXIgQXJrIHdhbGxldFxuYWx0IEFsaWNlIHNlbmRzIGEgMjRoLWZyb3plbiB0eCBlbWJlZGluZyBzYW1lIGFzc2V0XG5cdEFBTFQgLT4-IF9BTFQ6IDI0aC1mcm96ZW4gdHggZW1iZWRpbmcgc2FtZSBhc3NldFxuXHRfQUxUIC0tPj4gX0FMVDogRmVlcyBhcmUgZ2l2ZW4gdG8gYSBibG9ja1xuXHRfQUxUIC0-PiArQkFMVDogQm9iIGNhbiBjaGVjayB0aGUgQWx0IGFtb3VudCBvbiBoaXMgQWx0IHdhbGxldFxuXHRhbHQgQm9iIHNlbmRzIHRoZSBkZWZyZWV6aW5nIHR4IGNvbnRhaW5pbmcgdGhlIGFzc2V0IGNvbXBsZW1lbnRcblx0XHRCQUxUIC0-PiBfQUxUOiBkZWZyZWV6aW5nIHR4IGNvbnRhaW5pbmcgdGhlIGFzc2V0IGNvbXBsZW1lbnRcblx0XHRcdGFsdCBzaWduYXR1cmVzIGFuZCBhc3NldCBtYXRjaGVzIG9uIEFsdCBibG9ja2NoYWluXG5cdFx0XHRfQUxUIC0tPj4gX0FMVDogRmVlcyBhcmUgZ2l2ZW4gdG8gYSBibG9ja1xuXHRcdFx0X0FMVCAtPj4gQUFMVDogQWxpY2UgY2FuIHNlZSBhc3NldCBjb21wbGVtZW50IG9uIGhlciBBbHQgd2FsbGV0XG5cdFx0XHRCQUxUIC0-PkJBTFQ6IEFsdCBjb2lucyBhcmUgbm93IGF2YWlsYWJsZVxuXHRcdFx0Tm90ZSBvdmVyIEJBUkssQkFMVDogQm9iIGVuam95cyBoaXMgbmV3IEFsdCBjb2lucy5cblx0XHRcdGFsdCBBbGljZSBrbm93aW5nIHRoZSBhc3NldCBjb21wbGVtZW50IHNlbmRzIHRoZSBkZWZyZWV6aW5nIHR4XG5cdFx0XHRBQVJLIC0-PiBfQVJLOiBkZWZyZWV6aW5nIHR4IGNvbnRhaW5pbmcgdGhlIGFzc2V0IGNvbXBsZW1lbnRcblx0XHRcdFx0X0FSSyAtLT4-IF9BUks6IEZlZXMgYXJlIGdpdmVuIHRvIGEgYmxvY2tcblx0XHRcdFx0X0FSSyAtPj4gQkFSSzogQm9iIGtub3dzIGhpcyA0OGgtZnJvemVuIHR4IGlzIGFwcGxpZWRcblx0XHRcdFx0QUFSSyAtPj4gQUFSSzogQXJrIGNvaW5zIGFyZSBub3cgYXZhaWxhYmxlXG5cdFx0XHRcdE5vdGUgb3ZlciBBQVJLLEFBTFQ6IEFsaWNlIGVuam95cyBoZXIgbmV3IEFyayBjb2lucy5cblx0XHRcdGVsc2UgZWxzZVxuXHRcdFx0XHROb3RlIG92ZXIgQUFSSyxBQUxUOiBBbGljZSBsb3N0IGhlciBBbHQgY29pbnMgYW5kIG9ubHk8YnIvPmhhcyB0byBibGFtZSBoZXJzZWxmLi4uXG5cdFx0XHRlbmRcblx0XHRlbHNlIGVsc2Vcblx0XHRcdE5vdGUgb3ZlciBfQUxUOiBBbHQgYmxvY2tjaGFpbjxici8-cmVqZWN0cyB0cmFuc2FjdGlvbi5cblx0XHRcdE5vdGUgb3ZlciBCQUxULEFBTFQ6IEJvYiBhbmQgQWxpY2UgbG9zdCB0cmFuc2FjdGlvbiBmZWVzIHJlc3BlY3RpdmVseSBvbiBBcmsgYW5kIEFsdCBibG9ja2NoYWluLiBBbGljZSBjYW4gYmxhbWUgQm9iIHRvIGJlIHNvIGxhbWUgaW4gaGlzIHNpbXBsZSB0YXNrcyAhXG5cdFx0ZW5kXG5cdGVsc2UgZWxzZVxuXHRcdE5vdGUgb3ZlciBBQVJLLEFBTFQ6IEFsaWNlIGlzIGRpc2Fwb2ludGVkLCBub3Qgc3VycHJpc2VkPGJyLz5idXQgb25seSBsb3N0cyB0cmFuc2FjdGlvbiBmZWVzLi4uXG5cdFx0QkFMVCAtLT4gLV9BTFQ6IDI0aC1mcm96ZW4gdHggZXhwaXJlc1xuXHRlbmRcbmVsc2UgZWxzZVxuXHROb3RlIG92ZXIgQkFMVCxCQVJLOiBCb2IgaXMgZGlzYXBvaW50ZWQsIG5vdCBzdXJwcmlzZWQ8YnIvPiBidXQgb25seSBsb3N0cyB0cmFuc2FjdGlvbiBmZWVzLi4uXG5cdEFBUksgLS0-IC1fQVJLOiA0OGgtZnJvemVuIHR4IGV4cGlyZXNcbmVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) an adaptation of HTLC atomic swap based on a freezer/defreezer transaction pair.

### Freezer transaction
```json
{
	"type": 111,
	"fee": <int>,
	"timelock" <expiration_timestamp>,
	"amount": <int>,
	"senderId": <BOB_address>,
	"senderPublicKey": <hex>,
	"recipientId": <ALICE_address>,
	"vendorField": <ascii>,
	"asset": {
		"image": <hex_issued_from_preimage_with_specific_method>,
	},
	"signatures": <hex>,
	["signSignature": <hex>],
	"id": <freezer_id>
}
```
### Defreezer transaction
```json
{
	"type": 112,
	"fee": <int>,
	"amount": 0,
	"senderId": <ALICE_address>,
	"senderPublicKey": <hex>,
	"recipientId": <BOB_address>,
	"vendorField": <ascii>,
	"asset": {
		"freezer_id": <freezer_id>,
		"preimage": <ascii>,
		"method": "ecdsa:secp256k1:<verifyingKey>"
	},
	"signatures": <hex>,
	["signSignature": <hex>],
	"id": <hex>
}
```

### Different methods could be described in asset
```json
"asset": {
	"freezer_id": <freezer_id>,
	"preimage": <ascii>,
	"method": "nacl:<verifyingKey>",
}
"asset": {
	"freezer_id": <freezer_id>,
	"preimage": <ascii>,
	"method": "hash:sha256",
}
...
```

## Pseudo-code implementation
> this is a first draw and may be improved 

At transaction pool level, freezer tx are to be validated if wallet balance allows it. A defreezer tx is valid if described asset matches with the element sent before and if timelock did not expire. 
```python
[...]
FROZEN_TRANSACTIONS = {}
[...]
LAST_BLOCK_TIMESTAMP = getBlockchainHeight()["timestamp"]
[...]
for transaction in pool:
	[...]
	# if freezer transaction found
	if transaction["type"] == 111:
		address = transaction["senderId"]
		if transaction["timelock"] < LAST_BLOCK_TIMESTAMP and \
		   checkSignatures(transaction) and \
		   checkWalletBalance(address):
			validateTransaction(transaction)
	[...]
	# if defreezer transaction found
	if transaction["type"] == 112:
		address = transaction["recipientId"]
		freezer_tx = FROZEN_TRANSACTIONS.get(address, {}).get(transaction["asset"]["freezer_id"], False)
		if freezer_tx and \
		   freezer_tx["timelock"] > transaction["timelock"] and \
		   freezer_tx["timelock"] <= LAST_BLOCK_TIMESTAMP and \
		   freezer_tx["senderID"] == address and \
		   transaction["senderID"] == freezer_tx["recipientId"] and \
		   checkSignatures(transaction) and \
		   checkAssetMatch(transaction["asset"], freezer_tx["asset"]["image"]):
			validateTransaction(transaction)
	[...]
[...]
```

On relay side, all transactions are considered as valid. So balance computation could be done simply.

```python
[...]
# on block added
for transaction in block:
	[...]
	# if freezer tx found
	if transaction["type"] == 111:
		address = transaction["senderId"]
		# remove amount and fee from wallet
		WALLET[address]["balance"] -= transaction["amount"] + transaction["fee"]
		# keep track of frozen transaction
		FROZEN_TRANSACTIONS.get(address, {})[transaction["id"]] = transaction
	[...]
	# if defreezer transaction found
	if transaction["type"] == 112:
		# get the wallet address councerned by this frozen balance
		address = transaction["recipientId"]
		# get the associated frozen tx
		freezer_tx = FROZEN_TRANSACTIONS.get(address, {}).get(transaction["asset"]["freezer_id"], False)
		if freezer_tx and \
		   checkAsset(transaction["asset"], freezer_tx["asset"]["image"]) and \
		   freezer_tx["timelock"] <= block["timestamp"]:
			WALLET[transaction["recipientId"]]["balance"] += freezer_tx["amount"]
			FROZEN_TRANSACTIONS.get(address, {}).pop(freezer_tx["id"])
	[...]
[...]

# after last block added defreeze frozen balances where expiration reached
for address in FROZEN_TRANSACTIONS:
	for transaction in list(FROZEN_TRANSACTIONS[address].values()):
		if LAST_BLOCK_TIMESTAMP > transaction["timelock"]:
			tx = FROZEN_TRANSACTIONS[address].pop(transaction["id"])
			WALLET[address]["balance"] += tx["amount"]
```

**I think if this kind of atomic swap can be done between ark-forks, the path to do it directly with Bitcoin will be not so far...**

Any comments and ideas are welcome, it is a first draw proposal about atomic swap and may be subject to improvements.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by kristjank** [comment]
@Moustikitos thanks for this. We are also working quite heavy on the HTLC part, in a similar way as outlined by your proposal. 

This is something that will help us, when joining efforts. We will share more when we believe the specs are matured - so we can review and improve them together.

**Comment by Moustikitos** [comment]
Ok nice.

I think, the hardest part with HTLC  between ARK and Lightning Network will be the end user interface with desktop wallet.

Getting the right info from Ligtning Network using SCRIPT is matter of coding. Putting it simply for end user will be quite a huge task but possible with Desktop Wallet "plugability".

Maybe on ark-core side, ARK LOGIC would be most appropriate in Lightning Network interactions.

**Comment by kristjank** [comment]
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-102.md #102 Sharing updated docs from our side here. Thanks for your help with initial proposal. 

and yes the biggest part will be user interface, but this is scope of other tools and new AIPs. 

thanks @Moustikitos

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
